from pathlib import Path
import json

import sys, hashlib, re
OUT=Path(sys.argv[1]).resolve()
output_name=sys.argv[2] if len(sys.argv)>2 else 'gallery.html'
if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_.-]*\.html',output_name):raise ValueError('Safe local HTML name required')
if (OUT/output_name).exists(): raise FileExistsError('Fresh gallery HTML required')
data=json.loads((OUT/'manifest.json').read_text(encoding='utf-8'))
records=data['records']
function_count=len({r['base_id'] for r in records})
if not records or data['base_functions']!=function_count:raise ValueError('Incorrect function count in manifest')
if not re.fullmatch(r'[A-Za-z0-9_.-]+',data['version']):raise ValueError('Safe atlas version required')
for record in records:
    for key,digest_key in [('png','png_sha256'),('pdf','pdf_sha256'),('svg','svg_sha256'),('tsv','input_sha256'),('baseline_svg','baseline_svg_sha256')]:
        if key not in record: continue
        relative=Path(record[key])
        if relative.is_absolute() or ':' in record[key]: raise ValueError('Only local relative assets accepted')
        asset=(OUT/relative).resolve(strict=True)
        if not asset.is_relative_to(OUT):raise ValueError('Asset outside selected gallery')
        if hashlib.sha256(asset.read_bytes()).hexdigest()!=record[digest_key]:raise ValueError('Asset hash mismatch: '+record['id'])
    thumbnail=(OUT/record['thumbnail']).resolve(strict=True)
    if not thumbnail.is_relative_to(OUT):raise ValueError('Thumbnail outside gallery')

template=r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>科研绘图 · 逐图审美工作台</title>
<style>
:root{--ink:#253e3b;--muted:#687772;--line:#dfe5df;--paper:#f4f5ef;--accent:#2d6c61;--amber:#ad792e}
*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--paper);font-family:"Microsoft YaHei","PingFang SC",Arial,sans-serif;font-size:14px}
button,input,textarea,select{font:inherit}button,a{touch-action:manipulation}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #b79556;outline-offset:3px}
aside{position:fixed;top:0;bottom:0;left:0;width:242px;background:#fff;border-right:1px solid var(--line);padding:30px 20px;overflow-y:auto}.brand{font-size:12px;letter-spacing:2px;font-weight:700;color:var(--accent)}aside h1{font-size:24px;line-height:1.4;margin:14px 0 10px}aside p{color:var(--muted);font-size:12px;line-height:1.7}
.search{width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:8px;margin:18px 0 16px;background:#fafbf8}
.nav{display:flex;flex-direction:column;gap:5px}.nav button{border:0;text-align:left;padding:11px 10px;background:transparent;color:var(--muted);border-radius:7px;display:flex;justify-content:space-between;gap:5px}.nav button.active{background:#e8f0e9;color:var(--accent);font-weight:700}.nav small{font-size:11px}
.sidebottom{border-top:1px solid var(--line);margin-top:24px;padding-top:18px}.sidebottom a{color:var(--accent);line-height:2;text-decoration:none}main{margin-left:242px;padding:34px 34px 60px;max-width:1920px}.eyebrow{font-size:12px;letter-spacing:1px;color:var(--accent);font-weight:700}.hero{display:flex;justify-content:space-between;gap:24px;align-items:center}h2{font-size:32px;letter-spacing:-.5px;margin:12px 0}.intro{color:var(--muted);max-width:700px;line-height:1.8}.toolbar{display:flex;gap:9px;flex-wrap:wrap}.button{padding:10px 14px;border:1px solid var(--line);background:white;color:var(--ink);border-radius:7px;text-decoration:none;display:inline-block}.button.primary{background:var(--accent);border-color:var(--accent);color:#fff}.stats{display:flex;gap:20px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);margin:24px 0 25px;padding:16px 0;color:var(--muted);font-size:13px}.stats b{color:var(--ink);font-size:19px;margin-right:6px}.statusfilter{margin-left:auto;border:1px solid var(--line);border-radius:6px;padding:5px 8px;background:white;color:var(--ink)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px}.card{background:#fff;border:1px solid var(--line);border-radius:10px;overflow:hidden;transition:box-shadow .18s,transform .18s}.card:hover{box-shadow:0 9px 22px #1c37300d;transform:translateY(-2px)}.cardtop{padding:15px 16px 9px;display:flex;justify-content:space-between;align-items:center}.id{font-weight:700;letter-spacing:1px;color:var(--accent);font-size:13px}.pill{font-size:11px;padding:3px 7px;background:#f3f4ed;border-radius:4px;color:var(--muted)}.preview{display:block;border:0;background:#fff;width:100%;height:248px;cursor:zoom-in;padding:7px}.preview img{width:100%;height:100%;object-fit:contain}.cardbody{padding:12px 16px 16px;border-top:1px solid #f1f3ee}.card h3{font-size:16px;margin:0 0 7px;line-height:1.5}.variant{font-size:12px;color:var(--muted);margin-bottom:13px}.cardfoot{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--muted)}.cardfoot button{margin-left:auto;border:0;color:var(--accent);background:none}.smallnote{padding-top:7px;font-size:11px;color:var(--amber)}.empty{padding:80px 20px;color:var(--muted);text-align:center}.hint{color:var(--muted);line-height:1.8;font-size:12px;margin:25px 0}
dialog{border:0;border-radius:12px;padding:0;width:min(1430px,96vw);max-height:95vh;box-shadow:0 20px 80px #183d3930;color:var(--ink)}dialog::backdrop{background:#102e296b}.dialoghead{display:flex;align-items:center;gap:14px;padding:17px 22px;border-bottom:1px solid var(--line);background:#f9faf5;position:sticky;top:0;z-index:3}.dialoghead h3{font-size:19px;margin:0}.close{margin-left:auto;border:0;background:none;font-size:25px;color:var(--muted)}.details{display:grid;grid-template-columns:minmax(0,1fr) 310px;min-height:70vh}.plotspace{background:#edf0e9;padding:18px;min-width:0}.plottools{display:flex;gap:9px;align-items:center;margin-bottom:12px}.plottools label{font-size:12px;color:var(--muted)}.plottools select{padding:6px;border:1px solid var(--line);background:white}.viewbox{overflow:auto;max-height:70vh;background:#fff;border:1px solid var(--line);border-radius:6px}.viewbox img{display:block;width:100%;max-width:none;height:auto}.editpanel{padding:22px;background:white;overflow-y:auto}.editpanel h4{margin:0 0 10px;font-size:15px}.editpanel p{font-size:12px;color:var(--muted);line-height:1.7}.editpanel label{display:block;font-size:12px;color:var(--muted);margin:16px 0 6px}.editpanel select,.editpanel textarea{width:100%;border:1px solid var(--line);border-radius:6px;padding:9px;background:#fafbf8;color:var(--ink)}.editpanel textarea{min-height:145px;resize:vertical;line-height:1.7}.downloads{display:flex;gap:7px;margin-top:17px}.downloads a{font-size:12px;color:var(--accent);border:1px solid var(--line);padding:6px 9px;border-radius:5px;text-decoration:none}.detailnav{display:flex;gap:8px;margin-top:20px}.detailnav button{flex:1;padding:9px;border:1px solid var(--line);background:white;border-radius:6px;color:var(--ink)}.saved{color:var(--accent);font-size:11px;min-height:20px;margin-top:7px}.compare{display:grid;grid-template-columns:1fr 1fr;gap:15px;padding:20px;background:#edf0e9}.compare .pane{background:white;min-width:0;padding:12px}.compare img{width:100%;height:auto}.compare h4{margin:4px 0 12px}.toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);padding:12px 20px;background:var(--ink);color:white;border-radius:7px;z-index:10;display:none}
@media(min-width:1600px){.preview{height:270px}}@media(max-width:960px){aside{width:190px;padding:22px 14px}main{margin-left:190px;padding:24px 20px}.hero{display:block}.toolbar{margin-top:15px}.details{grid-template-columns:minmax(0,1fr) 260px}.stats{flex-wrap:wrap}.statusfilter{margin-left:0}}@media(max-width:650px){aside{position:static;width:100%;border-right:0;padding:18px}aside h1{font-size:21px}.nav{flex-direction:row;flex-wrap:wrap}.nav button{padding:7px}.sidebottom{display:none}.search{margin:10px 0}main{margin-left:0;padding:18px}.hero h2{font-size:26px}.grid{grid-template-columns:1fr}.details{display:block}.viewbox{max-height:55vh}.compare{grid-template-columns:1fr}.dialoghead h3{font-size:16px}}
</style></head><body>
<aside><div class="brand">FIGURE WORKBENCH</div><h1>逐图审美<br>工作台</h1><p>优化样式 · 版本 03<br>__FUNCTION_COUNT__ 类图形，__FIGURE_COUNT__ 种主要画法</p><input id="search" class="search" placeholder="搜索编号或图型，如 P10 / 热图" aria-label="搜索图形"><nav class="nav" id="nav"></nav><div class="sidebottom"><a href="科研绘图样式图册.pdf" target="_blank">打开完整 PDF 图册 ↗</a><br><a href="qa/overview.png" target="_blank">查看全部缩略总览 ↗</a><p>全部为合成演示数据。<br>用于判断样式与布局。</p></div></aside>
<main><div class="hero"><div><div class="eyebrow">从看见每张图，到确定你的样式</div><h2>先看优化版，再定你的审美。</h2><div class="intro">点击图形放大查看。记下颜色、字体、点线、坐标轴、图例或布局的调整要求，再导出修改清单。编号与之前的能力清单一致。</div></div><div class="toolbar"><button class="button" id="compare">并排比较 <span id="selectedcount">0</span>/2</button><button class="button primary" id="export">导出修改清单</button><button class="button" id="import">导入清单</button><input id="importfile" type="file" accept=".json,application/json" hidden></div></div>
<div class="stats"><span><b>__FUNCTION_COUNT__</b>绘图函数</span><span><b>__FIGURE_COUNT__</b>实际输出</span><span><b id="reviewed">0</b>已记录意见</span><select id="statusfilter" class="statusfilter" aria-label="筛选审美状态"><option value="all">全部状态</option><option value="unreviewed">尚未调整</option><option value="keep">保留当前样式</option><option value="tweak">需要微调</option><option value="redesign">需要重做布局</option></select></div>
<div class="grid" id="grid"></div><div id="empty" class="empty" hidden>没有匹配的图形。</div><p class="hint">图中英文标签用于观察当前绘图函数的字体和排版，页面说明为中文。笔记保存在当前浏览器本地；导出的清单可继续交给 Codex 修改。图册展示完整 Python 优化输出；五类新增函数的 R 导出已单独验证。原有图型可在详情中查看原版对照。</p></main>
<dialog id="detail"><div class="dialoghead"><span class="id" id="detailid"></span><h3 id="detailtitle"></h3><button class="close" id="closedetail" aria-label="关闭">×</button></div><div class="details"><div class="plotspace"><div class="plottools"><label>查看比例 <select id="zoom"><option value="1">适应窗口</option><option value="1.25">125%</option><option value="1.5">150%</option><option value="2">200%</option></select></label><span class="pill" id="detailvariant"></span><button class="button" id="beforeafter">原版／优化版对照</button></div><div class="viewbox"><img id="detailimage" alt="图形实际输出"></div></div><div class="editpanel"><h4>这一张，准备怎么改？</h4><p id="focus"></p><label for="decision">样式决定</label><select id="decision"><option value="unreviewed">尚未调整</option><option value="keep">保留当前样式</option><option value="tweak">需要微调</option><option value="redesign">需要重做布局</option></select><label for="notes">具体修改要求</label><textarea id="notes" placeholder="例如：降低背景点透明度；重点颜色改为橙紫；标签用 9pt；图例移到下方；减少右侧留白。"></textarea><div class="saved" id="saved"></div><label>输入与图形含义</label><p id="semantics"></p><div class="downloads" id="downloads"></div><div class="detailnav"><button id="prev">← 上一张</button><button id="next">下一张 →</button></div></div></div></dialog>
<dialog id="comparedialog"><div class="dialoghead"><h3>并排比较当前画法</h3><button class="close" id="closecompare" aria-label="关闭比较">×</button></div><div class="compare" id="comparebody"></div></dialog><dialog id="exportdialog"><div class="dialoghead"><h3>审美修改清单</h3><button class="close" id="closeexport" aria-label="关闭导出">×</button></div><div style="padding:22px"><p>下载清单，或复制下面的完整内容交给 Codex。</p><label for="exporttext">修改清单内容</label><textarea id="exporttext" readonly style="display:block;width:100%;height:42vh;margin:12px 0;font-family:monospace"></textarea><a class="button primary" id="downloadnotes" download="科研绘图_逐图审美修改清单.json">下载 JSON 文件</a></div></dialog><div class="toast" id="toast" role="status"></div>
<script>
const figures=__DATA__;const storageKey='figure-workbench-aesthetic-__VERSION__';let edits={};try{edits=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch(e){}
let category='全部图形',selected=new Set(),current=null;const categories=['全部图形',...new Set(figures.map(x=>x.category))];const labels={unreviewed:'尚未调整',keep:'保留',tweak:'微调',redesign:'重做布局'};const $=s=>document.querySelector(s);
function el(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node}
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2600)}
function nav(){const n=$('#nav');n.replaceChildren();for(const c of categories){const b=el('button',category===c?'active':'');b.append(el('span','',c),el('small','',String(c==='全部图形'?figures.length:figures.filter(x=>x.category===c).length)));b.onclick=()=>{category=c;nav();render()};n.append(b)}}
function filtered(){const q=$('#search').value.trim().toLowerCase();const s=$('#statusfilter').value;return figures.filter(f=>(category==='全部图形'||f.category===category)&&(!q||[f.id,f.base_id,f.title,f.variant,f.category].join(' ').toLowerCase().includes(q))&&(s==='all'||(edits[f.id]?.decision||'unreviewed')===s))}
function render(){const g=$('#grid');g.replaceChildren();const fs=filtered();for(const f of fs){const card=el('article','card');card.dataset.figureId=f.id;const top=el('div','cardtop');top.append(el('span','id',f.id),el('span','pill',f.category));const preview=el('button','preview');preview.setAttribute('aria-label','放大 '+f.id+' '+f.title);const img=el('img');img.src=f.thumbnail;img.alt=f.id+' '+f.title+' '+f.variant;img.loading='lazy';preview.append(img);preview.onclick=()=>openDetail(f.id);const body=el('div','cardbody');body.append(el('h3','',f.title),el('div','variant',f.variant));const foot=el('div','cardfoot');const label=el('label');const check=document.createElement('input');check.type='checkbox';check.checked=selected.has(f.id);check.setAttribute('aria-label','选择比较 '+f.id);check.onchange=()=>{if(check.checked&&selected.size>=2){check.checked=false;toast('一次选择两张进行比较');return}check.checked?selected.add(f.id):selected.delete(f.id);$('#selectedcount').textContent=selected.size};label.append(check,document.createTextNode('比较'));const button=el('button','',labels[edits[f.id]?.decision||'unreviewed']);button.onclick=()=>openDetail(f.id);foot.append(label,button);body.append(foot);if(edits[f.id]?.notes)body.append(el('div','smallnote','已记录具体修改要求'));card.append(top,preview,body);g.append(card)}$('#empty').hidden=fs.length>0;$('#reviewed').textContent=figures.filter(f=>edits[f.id]?.notes||(edits[f.id]?.decision&&edits[f.id]?.decision!=='unreviewed')).length}
function openDetail(id){current=figures.find(f=>f.id===id);$('#beforeafter').disabled=!current.baseline_svg;$('#detailid').textContent=id;$('#detailtitle').textContent=current.title;$('#detailvariant').textContent=current.variant;$('#detailimage').src=current.svg;$('#detailimage').alt=id+' '+current.title+' 实际SVG输出';$('#detailimage').style.width='100%';$('#zoom').value='1';$('#focus').textContent=current.description;$('#semantics').textContent=current.inputs+'。'+current.limits;$('#decision').value=edits[id]?.decision||'unreviewed';$('#notes').value=edits[id]?.notes||'';$('#saved').textContent='';const d=$('#downloads');d.replaceChildren();for(const [key,name]of [['svg','SVG'],['png','PNG'],['pdf','PDF'],['tsv','绘图数据']]){const a=el('a','',name);a.href=current[key];a.target='_blank';a.rel='noopener';d.append(a)}if(!$('#detail').open)$('#detail').showModal();location.hash=id}
function save(){if(!current)return;edits[current.id]={decision:$('#decision').value,notes:$('#notes').value,updated_at:new Date().toISOString()};try{localStorage.setItem(storageKey,JSON.stringify(edits));$('#saved').textContent='已保存在当前浏览器本地'}catch(e){$('#saved').textContent='当前浏览器不能保存，请导出修改清单'}render()}
$('#search').oninput=render;$('#statusfilter').onchange=render;$('#decision').onchange=save;$('#notes').oninput=save;$('#zoom').onchange=()=>$('#detailimage').style.width=(Number($('#zoom').value)*100)+'%';$('#closedetail').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);
function move(delta){const fs=filtered();const i=fs.findIndex(f=>f.id===current.id);if(fs.length)openDetail(fs[(Math.max(i,0)+delta+fs.length)%fs.length].id)}
$('#compare').onclick=()=>{if(selected.size!==2){toast('请先勾选两张图形');return}const b=$('#comparebody');b.replaceChildren();for(const id of selected){const f=figures.find(x=>x.id===id),pane=el('div','pane');pane.append(el('h4','',id+' '+f.title+' / '+f.variant));const img=el('img');img.src=f.svg;img.alt=id+' 比较';pane.append(img);b.append(pane)}$('#comparedialog').showModal()};$('#closecompare').onclick=()=>$('#comparedialog').close();
$('#beforeafter').onclick=()=>{if(!current?.baseline_svg)return;const b=$('#comparebody');b.replaceChildren();for(const [name,path] of [['原版',current.baseline_svg],['优化版',current.svg]]){const p=el('div','pane');p.append(el('h4','',current.id+' '+name));const img=el('img');img.src=path;img.alt=current.id+' '+name;p.append(img);b.append(p)}$('#comparedialog').showModal()};
let notesUrl=null;$('#export').onclick=()=>{const items=figures.filter(f=>edits[f.id]).map(f=>({id:f.id,title:f.title,variant:f.variant,input_sha256:f.input_sha256,svg_sha256:f.svg_sha256,...edits[f.id]}));const file={schema_version:1,atlas:'__VERSION__',exported_at:new Date().toISOString(),items};const content=JSON.stringify(file,null,2);$('#exporttext').value=content;if(notesUrl)URL.revokeObjectURL(notesUrl);notesUrl=URL.createObjectURL(new Blob([content],{type:'application/json'}));$('#downloadnotes').href=notesUrl;$('#exportdialog').showModal()};$('#closeexport').onclick=()=>$('#exportdialog').close();$('#import').onclick=()=>$('#importfile').click();$('#importfile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('size');const data=JSON.parse(await file.text());if(data.schema_version!==1||!Array.isArray(data.items))throw Error('schema');for(const item of data.items){if(figures.some(f=>f.id===item.id)&&['unreviewed','keep','tweak','redesign'].includes(item.decision)){edits[item.id]={decision:item.decision,notes:String(item.notes||'').slice(0,20000),updated_at:item.updated_at||new Date().toISOString()}}}localStorage.setItem(storageKey,JSON.stringify(edits));render();toast('修改清单已导入')}catch(err){toast('无法识别该修改清单')}e.target.value=''};
document.addEventListener('keydown',e=>{if($('#detail').open&&!['TEXTAREA','INPUT','SELECT'].includes(document.activeElement.tagName)){if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)}});nav();render();if(figures.some(f=>f.id===location.hash.slice(1)))openDetail(location.hash.slice(1));
</script></body></html>'''
template=template.replace('__FUNCTION_COUNT__',str(function_count)).replace('__FIGURE_COUNT__',str(len(records))).replace('__VERSION__',data['version'])
with (OUT/output_name).open('x',encoding='utf-8') as handle: handle.write(template.replace('__DATA__',json.dumps(records,ensure_ascii=False).replace('</','<\\/')))
print(json.dumps({'figures':len(records),'output':str(OUT/output_name)},ensure_ascii=False))
