args<-commandArgs(TRUE);stopifnot(length(args)==2,!dir.exists(args[1]));dir.create(args[1],recursive=TRUE)
skill<-dirname(normalizePath(sub('^--file=','',grep('^--file=',commandArgs(),value=TRUE))))
source(file.path(skill,'figure_core.R'));source(file.path(skill,'figure_publication.R'))
Sys.setlocale('LC_CTYPE','English_United States.utf8')
read<-function(n)read.delim(file.path(args[2],paste0(n,'.tsv')),check.names=FALSE)
cur<-read('curve');pr<-read('PR');mat<-read('matrix');interval<-read('forest');embedding<-read('features');rain<-read('raincloud')
pal<-c(A='#E98B2A',B='#7562A5');blocks<-c(one='#2D9C95',two='#4B88B5')
meta<-list(source='Explicitly synthetic software fixtures',palette=as.list(pal),input_unit='synthetic rows',experimental_unit='none - synthetic fixture',contrast='SYNTHETIC DEMO not biological results',denominator='defined synthetic table',model='none; software rendering',limits='known supplied ranges',filtering='all fixture rows',uncertainty='synthetic bounds not scientific CI',interpretation_limit='SYNTHETIC DEMO, no scientific evidence',synthetic=TRUE)
save<-function(p,d,n){export_figure(p,d,args[1],n,meta,width=7.1,height=5.5)}
save(plot_publication_curve(cur,pal,'ROC',c(A='A DEMO',B='B DEMO'),'SYNTHETIC DEMO ROC'),cur,'ROC')
save(plot_publication_curve(pr,pal,'PR',c(A='A DEMO',B='B DEMO'),'SYNTHETIC DEMO PR',.5),pr,'PR')
save(plot_aligned_matrix(mat,'Synthetic values',c(-2,2),block_palette=blocks,title='SYNTHETIC DEMO tiles'),mat,'tile')
save(plot_aligned_matrix(mat,'Synthetic values',c(-2,2),geometry='bubble',block_palette=blocks,title='SYNTHETIC DEMO bubbles'),mat,'bubble')
save(plot_publication_forest(interval,pal,'Synthetic estimate','Synthetic bounds','difference','SYNTHETIC DEMO intervals'),interval,'forest')
save(plot_feature_facets(embedding,'Synthetic expression',c(0,4),title='SYNTHETIC DEMO stored coordinates'),embedding,'features')
cloud<-plot_raincloud(rain,pal,'Synthetic score','synthetic observation','SYNTHETIC DEMO raincloud');stopifnot(identical(attr(cloud,'omics_spec')$density_groups,'A'));save(cloud,rain,'raincloud')
rejects<-0
reject<-function(expr){z<-tryCatch({force(expr);FALSE},error=function(e)TRUE);stopifnot(z);rejects<<-rejects+1}
reject(plot_aligned_matrix(mat[-1,],'x',c(-2,2)))
reject(plot_aligned_matrix(mat,'x',c(-1,1),block_palette=blocks))
bad<-mat;bad$row_count[1]<-3;reject(plot_aligned_matrix(bad,'x',c(-2,2),block_palette=blocks))
bad<-embedding;bad$x[1]<-100;reject(plot_feature_facets(bad,'x',c(0,4)))
reject(plot_feature_facets(embedding[-1,],'x',c(0,4)))
bad<-cur;bad$x[1]<-.5;reject(plot_publication_curve(bad,pal,'PR',c(A='A',B='B'),prevalence=.5))
reject(plot_publication_curve(cur,pal,'ROC',c(A='A')))
bad<-interval;bad$lower[1]<-.6;reject(plot_publication_forest(bad,pal,'x','x','difference'))
reject(plot_raincloud(rbind(rain,rain[1,]),pal,'x','unit'))
reject(plot_raincloud(rain,pal,'x',''))
stopifnot(rejects==10)
cat('R_EXPORTS=7 REJECTION_TESTS=',rejects,'\n')
