args <- commandArgs(trailingOnly=TRUE)
if(length(args)!=1||dir.exists(args[1])) stop('New test output directory required')
script <- sub('^--file=','',grep('^--file=',commandArgs(),value=TRUE)[1])
source(file.path(dirname(normalizePath(script)),'figure_core.R'))
source(file.path(dirname(normalizePath(script)),'figure_extensions.R'))
dir.create(args[1],recursive=TRUE); out <- args[1]
meta <- list(source='Synthetic regression fixture',palette='Declared in figure_spec',input_unit='test rows',experimental_unit='test subjects',contrast='DEMO',denominator='eligible test rows',model='none',limits='none',filtering='none',uncertainty='supplied test bounds',interpretation_limit='software validation only',synthetic=TRUE)
f <- data.frame(label=c('a','b'),estimate=c(1.4,.7),lower=c(1.1,.5),upper=c(1.8,.9))
total <- 0L
reject <- function(expr) {
  failed <- inherits(tryCatch(force(expr),error=function(e)e),'error')
  if(!failed) stop('Expected rejection')
  total <<- total+1L
}
p <- plot_forest(f,'HR','Synthetic interval','ratio')
built <- ggplot2::ggplot_build(p)
stopifnot(built$data[[1]]$xintercept==0) # log10(1) in built coordinates
stopifnot(attr(p,'omics_spec')$null_value==1,attr(p,'omics_spec')$effect_scale=='ratio')
reject(plot_forest(f,'HR','bounds'))
bad <- f; bad$lower[1] <- 0; reject(plot_forest(bad,'HR','bounds','ratio'))
reject(plot_forest(f,'HR','bounds','unknown'))
badmeta <- meta; badmeta$input_hash <- 'invented'; reject(export_figure(p,f,out,'bad_hash',badmeta))
badmeta <- meta; badmeta$source <- ' '; reject(export_figure(p,f,out,'empty_source',badmeta))
reject(export_figure(p,f[2:1,],out,'mismatched_rows',meta))
altered <- f; altered$estimate[1] <- 1.5; reject(export_figure(p,altered,out,'mismatched_values',meta))
sha <- digest::digest(file=script,algo='sha256')
reject(export_figure(p,f,out,'source_mismatch',meta,source_file=script,expected_source_sha256=paste(rep('0',64),collapse='')))
reject(export_figure(p,f,out,'source_missing',meta,expected_source_sha256=sha))
inject_render_failure <- function() {
  ns <- asNamespace('ggplot2'); original_save <- get('ggsave',ns); calls <- 0L
  failing_save <- function(...) { calls <<- calls+1L; if(calls==2L) stop('Intentional second-format failure'); original_save(...) }
  unlockBinding('ggsave',ns); assign('ggsave',failing_save,ns); lockBinding('ggsave',ns)
  on.exit({unlockBinding('ggsave',ns); assign('ggsave',original_save,ns); lockBinding('ggsave',ns)},add=TRUE)
  reject(export_figure(p,f,out,'retryable',meta))
}
inject_render_failure()
stopifnot(!dir.exists(file.path(out,'retryable')),!length(list.files(out,pattern='^[.]retryable',all.files=TRUE)))
files <- export_figure(p,f,out,'retryable',meta,source_file=script,expected_source_sha256=sha)
rec <- jsonlite::read_json(files[5],simplifyVector=TRUE)
stopifnot(rec$source_file_sha256==sha,rec$input_hash==digest::digest(file=files[4],algo='sha256'))
before <- tools::md5sum(files); reject(export_figure(p,f,out,'retryable',meta)); stopifnot(identical(before,tools::md5sum(files)))
lock <- file.path(out,'.reserved.lock'); dir.create(lock)
reject(export_figure(p,f,out,'reserved',meta)); stopifnot(dir.exists(lock)); unlink(lock,recursive=FALSE)
pairs <- data.frame(subject_id=c('a','a','b'),condition=c('A','B','A'),value=c(1,2,3))
reject(plot_paired(pairs,c(A='blue',B='red'),c('A','B'),'value'))
e <- data.frame(feature='a',contrast='b',estimate=1,lower=.5,upper=1.5,padj=0)
reject(plot_effect_matrix(e,'effect','difference'))
h <- data.frame(feature=c('g','g'),sample=c('s','s'),value=c(1,2),sample_group=c('A','B'),feature_block=c('X','X'))
reject(plot_annotated_heatmap(h,'value',c(A='blue',B='red'),c(X='green'),'signed'))
s <- data.frame(feature='x',score_a=.5,score_b=.7,delta=.3,lower_delta=.2,upper_delta=.4)
reject(plot_score_comparison(s,'AUC',c('A','B')))
z <- data.frame(feature='g',group='c',fraction=.5,value=1)
reject(plot_dot(z,'value','unknown','cells')); reject(plot_dot(z,'value','mean_all',''))
need('systemfonts'); stopifnot('Microsoft YaHei' %in% systemfonts::system_fonts()$family)
if(.Platform$OS.type=='windows') stopifnot(nzchar(Sys.setlocale('LC_CTYPE','English_United States.utf8')))
options(omics.font_family='Microsoft YaHei')
zh <- data.frame(sample_id=c('\u52a8\u7269\u7532','\u52a8\u7269\u4e59'),group=c('\u5bf9\u7167\u7ec4','\u5904\u7406\u7ec4'),value=c(1,2))
pal <- setNames(c('#35618F','#B84E35'),zh$group)
export_figure(plot_sample_points(zh,pal,'\u8868\u8fbe\u91cf\uff08\u6f14\u793a\uff09'),zh,file.path(out,'\u4e2d\u6587\u8def\u5f84'),'unicode',meta)
cat('PASS:',total,'rejection cases; ratio reference; input/source hashes; failed-export retry; existing-output preservation; Unicode path/font\n')
