args <- commandArgs(trailingOnly=TRUE)
if (length(args)!=1) stop('Usage: Rscript smoke_test.R NEW_OUTPUT_DIRECTORY')
if (dir.exists(args[1])) stop('Test directory must not already exist')
script <- sub('^--file=','',grep('^--file=',commandArgs(),value=TRUE)[1])
source(file.path(dirname(normalizePath(script)),'figure_core.R'))
source(file.path(dirname(normalizePath(script)),'figure_extensions.R'))
set.seed(1409)
pal <- c(Control='#35618F',Treated='#C45A2D')
meta <- list(source='Generated software fixture, seed 1409',input_unit='synthetic test units',experimental_unit='synthetic only',contrast='DEMO',denominator='see plotted table',model='none; renderer test',limits='no display truncation',filtering='none',uncertainty='demo bounds, not scientific CI',interpretation_limit='No scientific interpretation',synthetic=TRUE)
meta$palette <- 'Control=#35618F;Treated=#C45A2D;other scales as figure_core.R'
save_test <- function(p,d,id) export_figure(p,d,args[1],id,meta)
d <- data.frame(cell_id=paste0('c',1:80),x=rnorm(80),y=rnorm(80),group=rep(names(pal),each=40))
save_test(plot_embedding(d,pal),d,'embedding')
q <- data.frame(cell_id=d$cell_id,sample=d$group,value=abs(d$x)*1000)
save_test(plot_qc(q,'DEMO counts'),q,'qc')
s <- data.frame(sample_id=paste0('s',1:10),group=rep(names(pal),each=5),value=rnorm(10))
save_test(plot_sample_points(s,pal,'DEMO expression'),s,'samples')
f <- data.frame(label=c('Cohort A','Cohort B','Cohort C'),estimate=c(.3,-.2,.8),lower=c(-.1,-.6,.2),upper=c(.7,.2,1.4))
save_test(plot_forest(f,'DEMO effect','Synthetic bounds','difference'),f,'forest')
v <- data.frame(gene=paste0('g',1:80),log2FC=rnorm(80,sd=2),padj=10^runif(80,-5,0))
save_test(plot_volcano(v),v,'volcano')
z <- expand.grid(feature=paste0('gene',1:5),group=names(pal)); z$fraction <- runif(nrow(z)); z$value <- runif(nrow(z),0,3)
save_test(plot_dot(z,'DEMO mean','mean_all','All eligible demo cells'),z,'dot')
h <- expand.grid(feature=paste0('gene',1:8),sample=paste0('sample',1:6)); h$value <- rnorm(nrow(h))
save_test(plot_heatmap(h,'DEMO signed values'),h,'heatmap')
c <- expand.grid(sample=paste0('sample',1:4),celltype=names(pal)); c$count <- sample(10:90,nrow(c))
save_test(plot_composition(c,pal),c,'composition')
for (kind in c('ROC','PR','calibration')) {
  curve <- data.frame(model='DEMO',x=seq(0,1,length.out=20),y=seq(0,1,length.out=20))
  if(kind=='PR') curve$y <- 1-.5*curve$x
  save_test(plot_curve(curve,kind),curve,tolower(kind))
}
ratio <- f; ratio[c('estimate','lower','upper')] <- exp(ratio[c('estimate','lower','upper')])
save_test(plot_forest(ratio,'DEMO hazard ratio','Synthetic bounds','ratio'),ratio,'forest_ratio')
unsigned <- h; unsigned$value <- abs(unsigned$value)
save_test(plot_heatmap(unsigned,'DEMO nonnegative values',scale_type='sequential'),unsigned,'heatmap_sequential')
paired <- data.frame(subject_id=rep(c('s1','s2','s3'),each=2),condition=rep(c('Control','Treated'),3),value=c(1,2,2,1.5,1.2,2.4))
save_test(plot_paired(paired,pal,c('Control','Treated'),'DEMO value'),paired,'paired')
effects <- expand.grid(feature=c('T cells','B cells','Myeloid'),contrast=c('Contrast 1','Contrast 2'))
effects$estimate <- c(-.8,.3,.6,-.4,.1,.7); effects$lower <- effects$estimate-.3; effects$upper <- effects$estimate+.3; effects$padj <- c(.001,.1,.04,.2,1,.000001)
save_test(plot_effect_matrix(effects,'DEMO log odds ratio','log_ratio'),effects,'effect_matrix')
annotated <- h; annotated$sample_group <- ifelse(as.integer(sub('sample','',annotated$sample))<=3,'Control','Treated'); annotated$feature_block <- ifelse(as.integer(sub('gene','',annotated$feature))<=4,'Program A','Program B')
save_test(plot_annotated_heatmap(annotated,'DEMO signed values',pal,c('Program A'='#8172B2','Program B'='#55A868'),'signed'),annotated,'annotated_heatmap')
scores <- data.frame(feature=c('T cells','B cells','Myeloid'),score_a=c(.6,.72,.8),score_b=c(.8,.65,.85))
scores$delta <- scores$score_b-scores$score_a; scores$lower_delta <- scores$delta-.04; scores$upper_delta <- scores$delta+.04
export_figure(plot_score_comparison(scores,'DEMO AUC',c('Condition A','Condition B')),scores,args[1],'score_comparison',meta,width=9)
must_fail <- function(expr) {
  failed <- inherits(tryCatch(force(expr),error=function(e)e),'error')
  if(!failed) stop('Negative test unexpectedly passed')
}
bad <- f; bad$lower[1] <- 1; must_fail(plot_forest(bad,'effect','bounds','difference'))
bad <- z; bad$fraction[1] <- 2; must_fail(plot_dot(bad,'value','mean_all','cells'))
bad <- d; bad$cell_id[2] <- bad$cell_id[1]; must_fail(plot_embedding(bad,pal))
bad <- v; bad$padj[1] <- 0; must_fail(plot_volcano(bad))
must_fail(plot_embedding(d,pal[1]))
must_fail(plot_heatmap(h[-1,],'value'))
must_fail(export_figure(plot_forest(f,'effect','bounds','difference'),f,args[1],'forest',meta))
must_fail(export_figure(plot_forest(f,'effect','bounds','difference'),f,args[1],'../escape',meta))
must_fail(plot_sample_points(rbind(s,s[1,]),pal,'value'))
files <- list.files(args[1],full.names=TRUE,recursive=TRUE)
stopifnot(length(files)==102,all(file.info(files)$size>0))
receipts <- list.files(args[1],pattern='[.]json$',full.names=TRUE,recursive=TRUE)
stopifnot(length(receipts)==17)
for (r in receipts) {
  rec <- jsonlite::read_json(r,simplifyVector=TRUE)
  stopifnot(isTRUE(rec$synthetic),rec$status=='RENDERED_UNREVIEWED')
  for(n in names(rec$output_sha256)) stopifnot(identical(digest::digest(file=file.path(dirname(r),n),algo='sha256'),rec$output_sha256[[n]]))
  stopifnot(rec$input_hash==rec$output_sha256[[paste0(rec$figure_id,'.tsv')]])
}
cat('PASS: 17 synthetic figures x 6 files; 9 negative tests; verified output hashes; no biological analysis\n')
